name: Init Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 6"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Update Python
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -y update
          sudo apt-get install -y wget
          sudo apt-get install -y python2 
          sudo rm -rf /usr/bin/python
          sudo ln -s /usr/bin/python2 /usr/bin/python

      - name: Install Repo
        run: |
          git clone https://github.com/nbnbnb/repo
          sudo cp repo/repo /usr/bin/

          wget -O - https://raw.githubusercontent.com/nbnbnb/build-env-on-ubuntu-bionic/refs/heads/master/install.sh | sudo bash     

          # 由于上面的脚本更新过包，下面需要再次更新 Python 引用
          sudo rm -rf /usr/bin/python
          sudo ln -s /usr/bin/python2 /usr/bin/python      

          echo `python --version`
          echo `python3 --version`
