#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 Jolly <https://totoro.site>
# 
# <https://github.com/skytotwo/NanoPi-R1S-Build-By-Actions>
#
# Write by Jolly 2019/12/7
# last update at 2020/3/19

name: NanoPi-M2A OpenWrt Build

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 6 * * *'
  # release:
  #   types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
          
      - name: Update Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -y update
          sudo apt-get install -y wget
          sudo apt install python2
          sudo rm -rf /usr/bin/python
          sudo ln -s /usr/bin/python2 /usr/bin/python
          
      - name: Install Repo
        run: |
          git clone https://github.com/nbnbnb/repo
          sudo cp repo/repo /usr/bin/
          
      - name: Download Source
        run: |
          mkdir friendlywrt-s5p4418
          cd friendlywrt-s5p4418
          repo init -u https://github.com/nbnbnb/friendlywrt_mainfests -b 19_07_1 -m s5p4418.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          repo sync -c --no-clone-bundle -j8

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | sudo bash     

          sudo apt-get install g++-9
          sudo apt-get install gcc-9
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 50 --slave /usr/bin/g++ g++ /usr/bin/g++-9

      - name: Build OpenWrt
        run: |     
          sudo apt install python2
          sudo rm -rf /usr/bin/python
          sudo ln -s /usr/bin/python2 /usr/bin/python        
          cp s5p4418_config friendlywrt-s5p4418/friendlywrt/.config

          # Compile fail
          rm -rf friendlywrt-s5p4418/friendlywrt/package/network/services/hostapd
          
          # diy
          mkdir -p friendlywrt-s5p4418/friendlywrt/package/diy
          cd friendlywrt-s5p4418/friendlywrt/package/diy
          git clone https://github.com/nbnbnb/luci-app-vssr.git
          git clone https://github.com/nbnbnb/lua-maxminddb.git
                
          mkdir luci-app-openclash
          cd luci-app-openclash
          git init
          git remote add -f origin https://github.com/vernesong/OpenClash.git
          git config core.sparsecheckout true
          echo "luci-app-openclash" >> .git/info/sparse-checkout
          git pull --depth 1 origin master
          git branch --set-upstream-to=origin/master master
                                        
          # update patch
          cd ../../../tools/m4/patches
          wget https://raw.githubusercontent.com/keyfour/openwrt/2722d51c5cf6a296b8ecf7ae09e46690403a6c3d/tools/m4/patches/011-fix-sigstksz.patch

          cd ../../../..
                   
          ./build.sh nanopi_m2a.mk
          
